name: Lighthouse CI

on:
  push:
    branches: [main]

jobs:
  lighthouse:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5

      - name: Lighthouse CI
        uses: treosh/lighthouse-ci-action@v12
        with:
          urls: |
            https://www.surgex.pt
            https://www.surgex.pt/en
            https://www.surgex.pt/pt
          configPath: ./lighthouserc.js
          uploadArtifacts: true
          temporaryPublicStorage: true
